### ISSUE TITLE
Adding customer dashbroad

### ISSUE THREAD

**Issue by muhammedashfar7** [snipcart/snipcart-jekyll#2]
I am trying to add snipcart for my project but cannot add customer dasbroad. Is it available under test version?
I am using snipcart v3. Added user-login buttons. But customer dashbroad is not showing.

**Comment by JeanSebTr** [comment]
Hi @muhammedashfar7 !

It should work out of the box! Can you contact us on support (geeks@snipcart.com or the chat widget in the dashboard)? This will allow us to check your account configuration.
